services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: fastapi_app
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - db
    volumes:
      - ./web:/app/web
      - ./utils:/app/utils

  content_parser:
    build:
      context: .
      dockerfile: content_parser/Dockerfile
    container_name: content_parser
    depends_on:
      - rabbitmq
      - db
    volumes:
      - ./content_parser:/app/content_parser
      - ./utils:/app/utils

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata: