services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: robyn_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./web:/app/web
      - ./utils:/app/utils

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: